### ISSUE TITLE
Upper case words are not correctly tokenized

### ISSUE THREAD

**Issue by Yomguithereal** [henchc/LegaliPy#1]
Hello @henchc,

While implementing your method in JavaScript for the [Talisman](https://github.com/Yomguithereal/talisman) library (code [here](https://github.com/Yomguithereal/talisman/blob/master/src/tokenizers/syllables/legalipy.js)), I noticed that your `legalipy` method will incorrectly handle capitalized words.

Here is some code you can put in `__main__` to easily test the issue:

``` python
text = """History is the discovery, collection, organization, analysis, and presentation of information about past events. History can also mean a continuous, typically chronological record of important or public events or of a particular trend or institution. Scholars who write about history are called historians. It is a field of knowledge which uses a narrative to examine and analyse the sequence of events, and it sometimes attempts to objectively investigate the patterns of cause and effect that determine events. Historians debate the nature of history and its usefulness. This includes discussing the study of the discipline as an end in itself and as a way of providing "perspective" on the problems of the present. The stories common to a particular culture but not supported by external sources (such as the legends surrounding King Arthur) are usually classified as cultural heritage rather than as the "disinterested investigation" needed by the discipline of history. Events of the past prior to written record are considered prehistory."""

onsets = getonsets(text)

print(legalipy("History", onsets[0]))
print(legalipy("history", onsets[0]))
```

"History" will be tokenized as `['H', 'i', 'sto', 'ry']`
while "history" will be tokenized as `['hi', 'sto', 'ry']`

I can submit a pull request to fix this if you so desire.

Have a good day :)

**Comment by henchc** [comment]
thank you @Yomguithereal , just fixed it! I'll link your repo in the readme. I also just committed [SonoriPy](https://github.com/henchc/SonoriPy/blob/master/SonoriPy1.py), another syllabification algorithm but it must be slightly modified for the language (just declaring the hierarchy), so depending on the audience it may be useful. It will be more accurate than LegaliPy, which is a quick and dirty method.

**Comment by Yomguithereal** [comment]
Thanks @henchc. I'll check SonoriPy & see if I can port it to JavaScript also.

> which is a quick and dirty method

That is certainly the best quick & dirty method I found so far. Thanks for your work. Even if the produced syllabification is not always perfect, the count is often quite accurate.

One drawback I found however, is that for some languages where combinations of consonants & vowels are sounding as a single consonant (like the French "qu"), the algorithm is not really tuned to work. But I am sure this can be somewhat fixed by giving some hints to the onset training. What do you think?

**Comment by Yomguithereal** [comment]
The usage of 'y' as a consonant sometimes (like in the French "rayon" where it's pronounced 'j') also tackles the limits of the method.

**Comment by henchc** [comment]
Yes, French and English will probably show the worst performances due to a complicated orthography. "yo" is not recognized as a permissible onset because, to my knowledge, no, or very few, French words begin with "yo", so that may just be an anomaly. One possible fix for this (and possible improvement to SonoriPy) would be to first translate to IPA. Then it might find a word pronounced with the same onset, despite being spelled differently, and then be deemed permissible (although I can't think of any "yo" onset sounds in French with any spellings). There are probably dict lookup methods or even algorithms for IPA translations, I haven't looked into it too much. This would, however, require the user to identify the language.

As for "qu", I'm not sure if you mean in something like qu'est ce que, but one problem is that the algorithm doesn't account for vowel clusters or dipthongs _at all_. This would be relatively easy to build in though, but would require more input from the user (the original intention was 0 input from the user aside from a large text or corpus). You could just map all dipthongs and monophonemic vowel clusters to one special character and then map it back out at the end and it would solve most vowel issues. You would need the dipthongs and clusters as input though.

I'll let you know if I come up with a different way, I work with relatively resource-poor languages lacking dictionary lookup, so I'll be tweaking these in the future.

**Comment by henchc** [comment]
for what it's worth, combining the two (first implementing SonoriPy and then correcting with LegaliPy, i.e. fixing illegal onsets) is most accurate.

**Comment by Yomguithereal** [comment]
How concretely would you combine both? First tokenize with SonoriPy then LegaliPy, but how should the correction should be done?

**Comment by henchc** [comment]
Essentially run SonoriPy as it is (requiring hiearchy input from user), so just modifying lines 34-39 for the specific language, then take getonsets function from LegaliPy, iterate through each syllable yielded by SonoriPy and if the onset is not in the set of onsets deemed permissible (it will mostly be consonant clusters like "dl" or something), then assign everything up to the permissible onset to the previous syllable
